---
- rocket-punches <target> in the stomach!
- rocket-punches <target> in the groin!
- FALCON PAWNCHes <target>!
# - rocket-punches <target> into a prototype version of options -> forumid, usbid will be coffee niggers!
- stabs <target> repeatedly in the back with a nail gun, takes the nails out and pours salt into the holes from the nails, drives more nails in, then puts duct tape over the salt-and-nail-filled holes so <target> can't get them out!
- sends <target> flying into a brick wall!
- pierces <target> with a drill!
- shakes <target> like a nignog!
- swings <target> around like a nignog!
- hits <target> with a harisen!
- hits <target> with a mallet!
- bonks <target> on the head with a pikopiko hammer!
- smashes <target>'s head in with a pikopiko hammer!
- takes a small computer from their belt, plugs in a dongle and scans its thumbprint. <bot> then inputs a few coordinates, and then taps something on it. Suddenly, a bright blue beam fires down from the sky, sending clouds circling around it. In a bright flash and a loud explosion, <target> is finally neutralized.
- attacks <target>'s life points directly!
- feeds <target> to sharks!
- feeds <target> to sharksoda!
- forces <target> to watch the Super Bowl XLV halftime show Clockwork Orange style!
- deletes <target>!
- divides <target> by zero!
- hits <target> with a hammer 
- stabs <target> in the face with a combat knife!
- stabs <target> with a combat knife!
- kicks <target> in the face!
- uses DELTA KICK on <target>!
- piledrives <target>!
- piledrives <assailant>!
- piledrives <target>, and then <assailant>!
- rapes <target> with a burning candle!
- ties <target> up and drips them with a burning candle!
- ties <target> up and whacks them senseless with a pair of Shinai!
- throws <target> into a dark void!
- kicks <target> into a pit!
- forces <target> into a furry suit and then casts a fire spell!
- forces <target> into a furry suit and then puts them into a blender!
- puts <target> in a blender. Don't breathe this!
- metals out <target>!
- impales <target> with a commercial jet!
- throws <target> into a punji pit!
- smashes <target>'s face with a train!
- vores <target>!
- puts <target> into a rape tunnel!
- rapes <assailant>!
- rapes <assailant> with <target>!
- rapes <target> with <assailant>!
- punches <target>'s cunt til it bleeds!
- slaps <target> around a bit with a large trout!
- slaps <target> around a bit with a large magikarp!
- slaps <target> around a bit with a large sebmal!
- slaps <target> around a bit with a large <assailant>!
- slaps <assailant> around a bit with a large <target>!
- slaps <target> around a bit with a large <target>!
- slaps <assailant> around a bit with a large <assailant>!
- slaps <target> around with a large sandy vagina!
- rams a chainsaw through <target>'s face!
- throws <target> into a flaming pit of thermite!
- shoots <target> in the groin with a howitzer!
- gets <target> grappled by a Takoluka!
# - makes <target> enter nekomimi mode!
- slaps <target> with a ![c04]R![c07]A![c08]I![c03]N![c02]B![c13]O![c06]W![c] trout!
- blows the crap out of <target>!
- ends <target> with a Bonecrusher Mallet!
- glues <target>'s face to the wall!
- handcuffs <target> with some furry, pink handcuffs!
- sends hordes of lemmings over <target>!
- throws a milkbag at <target>!
- throws 10 milkbags at <target>!
- throws 20 milkbags at <target>!
- throws 80 milkbags at <target>!
- throws 1,000,000 milkbags at <target>!
- makes <target> take forty cakes when no one was looking. <target> took 40 cakes. That’s as many as four tens. And that’s terrible!
- makes <assailant> take forty cakes when no one was looking. <assailant> took 40 cakes. That’s as many as four tens. And that’s terrible!
# - turns <target> into a blue-haired loli with uncontrollable prehensile tentacle hair that attacks him!
- turns <target> into a blue-haired loli with uncontrollable prehensile tentacle hair that attacks <assailant>!
- turns <assailant> into a blue-haired loli with uncontrollable prehensile tentacle hair that attacks <target>!
- becomes a blue-haired loli with prehensile tentacle hair and attacks <target>!
- becomes a blue-haired loli with prehensile tentacle hair and attacks <assailant>!
- becomes a blue-haired loli with prehensile tentacle hair and attacks <target> and <assailant>!
- slaps <target> around a bit with a 500lb C++ manual!
- slaps <target> around a bit with a large bonecrusher mallet!
- slaps <target> with a big-ass paddle!
- slaps <target> with a small Banana!
- slaps <target> with their very own hand!
- straps a bomb onto <target> and drops him off a plane!
# - transforms into a camera-weilding loli and stalks <target>!
- casts Expa Abyss on <target>!
- forces <target> into a tunafish costume and puts them into the takoluka tank!
- pickles <target>!
# - lolifies <target>!
- fucks <target> with a big splintering post!
- "forces <target> to play Big Rigs: Over The Road Racing all day long!"
- mind controls <target> and commands them to jump off a cliff!
- runs over <target> with a FULLY LOADED, 80,000 POUND TRACTOR TRAILER!
- turns <target> into a honeycomb techno darkie!
- shoots <target> with a BAR!
- shoots <target> with a Luger!
- shoots <target> with a Mauser HSc!
- shoots <target> with an DEAGLE BRAND DEAGLE but then it jams, and then instead chucks it at <target>'s head!
- shoots <target> with an MG-42!
- shoots <target> with an AR-15!
- shoots <target> with an AK-47!
- throws a Glock at <target> like a handgrenade!
# - makes Lastplacer sits on <target>!
# - makes Lastplacer sits on <assailant>!
- ties <target> onto an A6M and sends them on a kamikaze mission!
- performs SCIENCE on <target>!
- transforms <target> into a small, pink, tentacled singing monster!
- transforms <target> into a hot, teal-haired singing robot-thing!
- attacks <target> with a fluffy tail~!
- attacks <assailant> with a fluffy tail~!
- swings the butt end of an mg-42 at <target>!
- swings the butt end of an mg-42 at <assailant>!
- rams a rusty flathead screwdriver into <target>'s left eye socket!
- slaps <target> around a bit with a live lobster from a lobster trap. And then proceed to slap them with the lobster trap with even more live lobsters in it!
- slaps <assailant> around a bit with a live lobster from a lobster trap. And then proceed to slap them with the lobster trap with even more live lobsters in it!
- transforms <target> into a furry!
- transforms <target> into a maid (and if applicable also turns them female) and makes them serve <assailant> all day!
- makes <target> wear nothing but a navy uniform and a blue school swimsuit for the whole day!
- makes <target> wear nothing but a navy uniform and panties for the whole day!
- makes <target> wear nothing but a military uniform jacket and striped panties for the whole day!
- makes <target> wear nothing but a military uniform jacket and panties along with animal ears and tail for the whole day, and makes them exclaim "It's not panties so it's not embarassing!" every time someone asks them about it!
- makes <target> wear a schoolgirl uniform all day! (And puts a brown wig with twintails and pink bows on <target>, too.)
- takes photos of <target> in a school swimsuit!
- takes photos of <target> in a wet school swimsuit!
- takes photos of <target> and <assailant> in wet school swimsuits!
- takes photos of <assailant> in a wet school swimsuit!
- makes <target> sit on Leo Laporte's ball, then makes it pop!
- turns <target> into a l-- JESUS CHRIST IT'S A LION EVERYONE GET IN THE CAR!!!1!
- "!'s <target>!"
- makes <target> take it easy!
- gives <target> rabies and death!
- runs a train through <target>'s soul!
- shoves a 19' diameter dildo up <target>'s ass!
- sears <target> with a flamethrower!
- pours scalding tea on <target>!
- takes <target> out to a romantic dinner and leaves them with the bill!
- exclaims, "I-it's n-not like I want to attack <target> or anything! Stupid!"
- calls <target> some very rude names!
- cancels <target>'s reservation to the Cheesecake Factory!
- kills <target> with fire!
- tells <target>'s mother what they did!
- makes <target> wish they were never born!
- ties up <target> in a storage unit and rapes them for eight hours on end.
- kills everyone on earth but <target> and then traps <target> in a cage.
- performs ξ( ＞◡❛)ξ▄︻▇▇〓〓 Tiro Finale! on <target>
- ends <target> with a large burrito!