---
- rocket-punches <target> in the stomach!
- rocket-punches <target> in the groin!
- FALCON PAWNCHes <target>!
- stabs <target> repeatedly in the back with a nail gun, takes the nails out and pours salt into the holes from the nails, drives more nails in, then puts duct tape over the salt-and-nail-filled holes so <target> can't get them out!
- sends <target> flying into a brick wall!
- pierces <target> with a drill!
- shakes <target> like a idiot!
- swings <target> around like a idiot!
- hits <target> with a harisen!
- hits <target> with a mallet!
- bonks <target> on the head with a large hammer!
- smashes <target>'s head in with a large hammer!
- bonks <target> on the head with a pikopiko hammer!
- smashes <target>'s head in with a pikopiko hammer!
- takes a small computer from their belt, plugs in a dongle and scans its thumbprint. <bot> then inputs a few coordinates, and then taps something on it. Suddenly, a bright blue beam fires down from the sky, sending clouds circling around it. In a bright flash and a loud explosion, <target> is finally neutralized.
- attacks <target>'s life points directly!
- feeds <target> to sharks!
- forces <target> to watch the Super Bowl XLV halftime show Clockwork Orange style!
- deletes <target>!
- divides <target> by zero!
- hits <target> with a hammer!
- stabs <target> in the face with a combat knife!
- stabs <target> with a combat knife!
- kicks <target> in the face!
- uses DELTA KICK on <target>!
- piledrives <target>!
- piledrives <assailant>!
- piledrives <target>, and then <assailant>!
- rapes <target> with a burning candle!
- ties <target> up and drips them with a burning candle!
- ties <target> up and whacks them senseless with a pair of Shinai!
- throws <target> into a dark void!
- kicks <target> into a pit!
- forces <target> into a furry suit and then casts a fire spell!
- forces <target> into a furry suit and then puts them into a blender!
- puts <target> in a blender. Don't breathe this!
- metals out <target>!
- impales <target> with a commercial jet!
- throws <target> into a punji pit!
- smashes <target>'s face with a train!
- vores <target>!
- puts <target> into a rape tunnel!
- rapes <assailant>!
- rapes <assailant> with <target>!
- rapes <target> with <assailant>!
- punches <target>'s cunt til it bleeds!
- slaps <target> around a bit with a large trout!
- slaps <target> around a bit with a large magikarp!
- slaps <target> around a bit with a large sebmal!
- slaps <target> around a bit with a large <assailant>!
- slaps <assailant> around a bit with a large <target>!
- slaps <target> around with a large sandy vagina!
- rams a chainsaw through <target>'s face!
- throws <target> into a flaming pit of thermite!
- shoots <target> in the groin with a howitzer!
- gets <target> grappled by a Takoluka!
- ! "slaps <target> with a \x0304R\x0307A\x0308I\x0303N\x0302B\x0313O\x0306W\x03 trout!"
- blows the crap out of <target>!
- ends <target> with a Bonecrusher Mallet!
- glues <target>'s face to the wall!
- sends hordes of lemmings over <target>!
- throws a milkbag at <target>!
- throws 10 milkbags at <target>!
- throws 20 milkbags at <target>!
- throws 80 milkbags at <target>!
- throws 1,000,000 milkbags at <target>!
- turns <target> into a blue-haired loli with uncontrollable prehensile tentacle hair that attacks <assailant>!
- turns <assailant> into a blue-haired loli with uncontrollable prehensile tentacle hair that attacks <target>!
- becomes a blue-haired loli with prehensile tentacle hair and attacks <target>!
- becomes a blue-haired loli with prehensile tentacle hair and attacks <assailant>!
- becomes a blue-haired loli with prehensile tentacle hair and attacks <target> and <assailant>!
- slaps <target> around a bit with a 500lb C++ manual!
- slaps <target> around a bit with a large bonecrusher mallet!
- slaps <target> with a big-ass paddle!
- slaps <target> with a small Banana!
- slaps <target> with their very own hand!
- straps a bomb onto <target> and drops them off a plane!
- casts Expa Abyss on <target>!
- forces <target> into a tunafish costume and dunks them into the takoluka tank!
- pickles <target>!
- fucks <target> with a big splintering post!
- "forces <target> to play Big Rigs: Over The Road Racing all day long!"
- mind controls <target> and commands them to jump off a cliff!
- runs over <target> with a FULLY LOADED, 80,000 POUND TRACTOR TRAILER!
- shoots <target> with a BAR!
- shoots <target> with a Luger!
- shoots <target> with a Mauser HSc!
- shoots <target> with a DEAGLE BRAND DEAGLE!
- attempts to shoot <target> with an DEAGLE BRAND DEAGLE, but then it jams, and instead chucks it at <target>'s head, square on the forehead!
- shoots <target> with an MG-42!
- shoots <target> with an AR-15!
- shoots <target> with an AK-47!
- throws a Glock at <target> like a handgrenade!
- ties <target> onto an A6M and sends them on a kamikaze mission!
- performs SCIENCE on <target>!
- swings the butt end of an mg-42 at <target>!
- swings the butt end of an mg-42 at <assailant>!
- rams a rusty flathead screwdriver into <target>'s left eye socket!
- rams a rusty flathead screwdriver into <target>'s right eye socket!
- slaps <target> around a bit with a live lobster from a lobster trap. And then proceed to slap them with the lobster trap with even more live lobsters in it!
- slaps <assailant> around a bit with a live lobster from a lobster trap. And then proceed to slap them with the lobster trap with even more live lobsters in it!
- turns <target> into a l-- JESUS CHRIST IT'S A LION EVERYONE GET IN THE CAR!!!1!
- gives <target> rabies and death!
- runs a train through <target>'s soul!
- shoves a 19' diameter dildo up <target>'s ass!
- slaps <target> around with a large black rubber dildo!
- sears <target> with a flamethrower!
- pours scalding tea on <target>!
- takes <target> out to a romantic dinner and leaves them with the bill!
- exclaims, "I-it's n-not like I want to attack <target> or anything! Stupid!"
- calls <target> some very rude names!
- cancels <target>'s reservation to the Cheesecake Factory!
- kills <target> with fire!
- tells <target>'s mother what they did!
- makes <target> wish they were never born!
- ties up <target> in a storage unit and rapes them for eight hours on end.
- kills everyone on earth but <target> and then traps <target> in a cage.
- performs ξ( ＞◡❛)ξ▄︻▇▇〓〓 Tiro Finale! on <target>!
- ends <target> with a large burrito!
- impales <target> with a wooden effigy of Spongebob!
- punches <target>!
- kicks <target>!
- forces <target> to pull out their fingernails one... by... one.
- forcefully transforms <target> into Platinum The Trinity!
- fills every one of <target>'s orifaces with poutine!
- fists <target> in the ass!
- injects <target> with blue paint!
- makes <target> wear nothing but a navy uniform top and a blue school swimsuit for the whole day!
- makes <target> wear nothing but a navy uniform top and panties for the whole day!
- makes <target> wear nothing but a military uniform jacket and striped panties for the whole day!
- forces <target> wear nothing but a military uniform jacket and panties along with animal ears and tail for the whole day, and makes them exclaim "It's not panties so it's not embarassing!" every time someone asks them about it!
- makes <target> wear a schoolgirl uniform all day! (And puts a brown wig with twintails and pink bows on <target>, too.)
- takes photos of <target> in a school swimsuit!
- takes photos of <target> in a wet school swimsuit!
- takes photos of <target> and <assailant> in wet school swimsuits!
- takes photos of <target> and <assailant> in school swimsuits, and then <bot> sets the camera on a timer and gets in on the action, hugging (and secretly feels up) the two! Wee~!
- takes photos of <assailant> in a wet school swimsuit!
- gropes and molests <target>~
- punches <target> behind the cock!
- punches <target> in the dick!
- punches <target> in the colon!
- punches <target> in the bush!
- bizarro-supermans <target>!
- bites <target>'s hand.
- bites <assailant>'s hand.
- assassinates <target> with a sniper rifle from a high-up building.
- shoves a dragon dildo up <target>'s ass!
- Seals <target> away in a Clow Card!
- Seals <target> away in a Sakura Card!
- summons The Arrow card, and pierces <target>!
- summons The Big card, and turns <target> into a giant!
- summons The Bubbles card, and forces <target> to take a bath!
- summons The Change card, and genderbends <target>!
- summons The Cloud card, and sends <target> into the sky!
- summons The Create card, and creates a copy of <assailant> that attacks <target>!
- summons The Dark card, and sends <target> into eternal darkness!
- summons The Dash card, and dashes toward <target>, grabbing them and taking them away to a secret place where they do... things.
- summons The Dream card, and makes <target> have a bad dream!
- summons The Earthy card, and traps <target> in rock and soil!
- summons The Erase card, and erases <target>'s clothes!
- summons The Fight card, and starts a sparring match with <target>, beating them easily!
- summons The Firey card, and sets <target> on fire!
- summons The Float card, and makes <target> float into space!
- summons The Flower card, and makes <target> wear a crown of flowers (that seem to have some control over them)!
- summons The Fly card, and flies off with <target> to a... place.
- summons The Freeze card, and freezes <target> in place!
- summons The Glow card, and makes <target> like a bioluminescent squid(girl)!
- summons The Illusion card, and makes <target>'s thoughts reality to them!
- summons The Jump card, and makes <target> neverendingly jump around!
- summons The Libra card, and determines that whatever <target> last said is a lie!
- summons The Light card, and dispells the darkness surrounding <target>, and then whacks them in the head!
- summons The Little card, and shrinks <target> down to pint-size!
- summons The Lock card, and makes <target> repulsive to anyone who touches them!
- summons The Loop card, and makes <target> run in a marathon forever!
- summons The Maze card, and traps <target> in a Escheresque maze with no hope of escape!
- summons The Mirror card, and clones <target>, making the clone the opposite of them!
- summons The Mist card, and dissolves <target>'s clothes off!
- summons The Move card, and moves <target> over an open punji pit!
- summons The Power card, and in conjunction with Fight and dash, kicks <target>'s ass!
- summons The Rain card, and makes <target> all soggy!
- summons The Return card, and makes <target> watch their parents concieving them!
- summons The Sand card, and traps <target> in sand!
- summons The Shadow card, and makes <target> disappear from sight!
- summons The Shield card, and makes <target> untouchable by anyone!
- summons The Shot card, and makes the card constantly shoot <target> until they're destroyed!
- summons The Silent card, and makes <target> unable to talk!
- summons The Sleep card, and makes <target> fall asleep!
- summons The Snow card, and makes <target> turn into a snowman!
- summons The Storm card, and makes a storm cloud constantly hover over <target>'s head!
- summons The Sweet card, and makes <target> so tasty that everyone would want to lick them!
- summons The Sword card, and swordplays with <target>, easily defeating them!
- summons The Thunder card, and summons a bolt of lightning which hits <target>, singeing their whole body!
- summons The Time card, drops <target>'s pants, and then reseals the card!
- summons The Twin card, and splits <target> into identical twins!
- summons The Voice card, and takes away <target>'s voice!
- summons The Watery card, and waterlogs <target>!
- summons The Wave card, and buries <target> under a feet of water!
- summons The Windy card, and binds <target>, exposing them for a final attack!
- summons The Wood card, and entangles <target> in its branches!- 
