---
mli:
  My site: "http://insomniafanfics.weebly.com"
  Tumblr: "http://mylittleinsomnia.tumblr.com"
  Facebook: "http://www.facebook.com/profile.php?id=100001428581452"
  PonySquare: "http://ponysquare.com/profile-2220/"
  Twitter: "https://twitter.com/#!/DJINs0mnIAK"
  Skype: "legit.sketchy"
  E-mail: "insomnia@ponify.me"
  XboxLIVE Gamertag: "ThatGuyEcho"
  Steam: "http://steamcommunity.com/id/mylittleinsomnia"
ponytoast:
  Email: "theponytoast@gmail.com"
  Twitter: "@TrueEquestria"
  Tumblr: "http://ponytoast.tumblr.com"
  BlogTalkRadio: "http://blogtalkradio.com/djzan"
  PonySquare: "http://ponysquare.com/profile-2143/"
  Facebook: "http://www.facebook.com/TheRealPonyToast"
  SoundCloud: "http://soundcloud.com/ponytoast"
  DeviantArt: "http://phdrillsergeant.deviantart.com/"
  Steam: "PonyToast"