---
mli:
  My site: http://insomniafanfics.weebly.com
  Tumblr: http://mylittleinsomnia.tumblr.com
  Facebook: http://www.facebook.com/profile.php?id=100001428581452
  PonySquare: http://ponysquare.com/profile-2220/
  Twitter: https://twitter.com/#!/DJINs0mnIAK
  Skype: legit.sketchy
  E-mail: insomnia@ponify.me
  XboxLIVE Gamertag: ThatGuyEcho
  Steam: http://steamcommunity.com/id/mylittleinsomnia
ponytoast:
  Tumblr: ponytoast.tumblr.com
  PonySquare: http://ponysquare.com/profile-2143/
  Skype: PonyToast
  BTR: http://blogtalkradio.com/djzan
  Twitter: "@TrueEquestria"
  E-mail: ponytoast@musician.org