---
!ruby/sym consumer_key: 6YbpJoPLCVLLMpGF7FbYA
!ruby/sym consumer_secret: XtyPHeDSSW4JrmfRQ7YwRn0uF9KXsUEho0k9CWv4
!ruby/sym oauth_token: 3086851-z7oH688BN3BQR9ouSqqDh4X7YDWxzwu7W0ivz8wqJl
!ruby/sym oauth_token_secret: N6D5R3LsdwqRU3hj6CSDJTdtuMOdwzbWwoqseROCa3o